MJCF to SDF: Added geometry defaults
gazebosim/gz-mujoco pull request #43
Opened 2022-05-24 15:37 UTC by ahcorde

Signed-off-by: ahcorde <ahcorde@gmail.com>
# 🎉 New feature

## Summary

You can define some defaul values in mujoco:

```xml
   <default>
     <geom type="capsule" mass="1"/>
   </default>
```

This PR allows to read these values and set them

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-05-31 23:02 UTC, azeey requested changes
I've left a comment on the logic of processing default classes. My preference would be to put all the default class processing into a single
module instead of duplicating them in each conversion file so that we only have one place to fix if we find bugs down the road.

2022-06-01 12:25 UTC, ahcorde commented on mjcf_to_sdformat/tests/resources/test_mujoco.xml
>  <mujoco>
https://github.com/gazebosim/gz-mujoco/pull/43/commits/7e508b314f542f9e04de279dc4a740e2fadd7031

2022-06-01 12:25 UTC, ahcorde commented on mjcf_to_sdformat/mjcf_to_sdformat/converters/link.py
> +                    geom.set_attributes(**{k: v})
https://github.com/gazebosim/gz-mujoco/pull/43/commits/7e508b314f542f9e04de279dc4a740e2fadd7031

2022-06-01 12:25 UTC, ahcorde commented on mjcf_to_sdformat/mjcf_to_sdformat/converters/world.py
> +                       default_classes=[]):
https://github.com/gazebosim/gz-mujoco/pull/43/commits/7e508b314f542f9e04de279dc4a740e2fadd7031

2022-06-01 12:25 UTC, ahcorde commented on mjcf_to_sdformat/tests/resources/test_defaults.xml
> +<mujoco>
https://github.com/gazebosim/gz-mujoco/pull/43/commits/7e508b314f542f9e04de279dc4a740e2fadd7031

2022-06-01 12:25 UTC, ahcorde commented on mjcf_to_sdformat/mjcf_to_sdformat/converters/link.py
> +                geom.set_attributes(**{k: v})
https://github.com/gazebosim/gz-mujoco/pull/43/commits/7e508b314f542f9e04de279dc4a740e2fadd7031

2022-06-01 20:39 UTC, azeey approved these changes

2022-06-01 20:39 UTC, azeey commented on mjcf_to_sdformat/mjcf_to_sdformat/converters/link.py
> +                geom.set_attributes(**{k: v})
Also addressed by #61

2022-06-01 20:39 UTC, azeey commented on mjcf_to_sdformat/mjcf_to_sdformat/converters/link.py
> +    if geom.dclass is not None:
Also addressed by #61

2022-06-01 21:00 UTC, merged