Add conversion for SDFormat Links
gazebosim/gz-mujoco pull request #5
Opened 2022-05-04 02:52 UTC by azeey

# 🎉 New feature

## Summary
Builds on top of #2 to add conversion for links.

## Test it
Run unit tests

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-05-04 08:38 UTC, ahcorde approved these changes

2022-05-10 20:43 UTC, ahcorde requested changes

2022-05-10 20:43 UTC, ahcorde commented on sdformat_mjcf/sdformat_mjcf/converters/link.py
> +
```suggestion
    for vi in range(link.visual_count()):
        vis = link.visual_by_index(vi)
        if vis.geometry() is not None:
            add_visual(body, vis, pose_resolver=pose_resolver)

```

2022-05-10 21:26 UTC, azeey commented on sdformat_mjcf/sdformat_mjcf/converters/link.py
> +
https://github.com/gazebosim/gz-mujoco/pull/5/commits/2e54b846be937d328dff7d04ac8da1edf7dfc0fa

2022-05-10 21:26 UTC, azeey commented
I've added more tests in https://github.com/gazebosim/gz-mujoco/pull/5/commits/3f481f26708e0faf59fbee4d33fd593b5a417641 to increase test coverage. @ahcorde PTAL.

2022-05-10 22:09 UTC, ahcorde approved these changes

2022-05-12 05:16 UTC, scpeters reviewed
this looks reasonable to me. I would just consider adding an expectation on the exact value of the `fullinertia` attribute (see https://github.com/gazebosim/gz-mujoco/commit/175b5d19b12370753edfb2348a912aa03adbbc78)

2022-05-12 21:09 UTC, azeey commented
> this looks reasonable to me. I would just consider adding an expectation on the exact value of the `fullinertia` attribute (see [175b5d1](https://github.com/gazebosim/gz-mujoco/commit/175b5d19b12370753edfb2348a912aa03adbbc78))

Thanks Steve! Are those values based on a known shape?

2022-05-12 21:28 UTC, merged

2022-05-12 22:04 UTC, scpeters commented
> Thanks Steve! Are those values based on a known shape?

Yes, they are based on a box with relative dimensions 1x4x9. I started with the values in [this test case](https://github.com/gazebosim/gz-math/blob/ign-math6/src/MassMatrix3_TEST.cc#L763-L771) but increased the mass by a factor of 32 (12 -> 384) to avoid decimals in the inertial values (aside from `sqrt(6)`). Looking again the values could all be reduced by a factor of 4, but I think it works either way.